# Generated by Django 3.2.3 on 2023-07-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientspecification',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
