# Generated by Django 3.2.3 on 2023-07-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tag_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tagrecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='tagrecipe',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='userfavoritedrecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='userfavoritedrecipe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usershoppingcart',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='usershoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='IngredientSpecification',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagRecipe',
        ),
        migrations.DeleteModel(
            name='UserFavoritedRecipe',
        ),
        migrations.DeleteModel(
            name='UserShoppingCart',
        ),
    ]
