# Generated by Django 3.2.3 on 2023-08-02 11:11

import colorfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavoritedrecipe',
            options={'verbose_name': 'Любимый рецепт', 'verbose_name_plural': 'Любимые рецепты'},
        ),
        migrations.AlterModelOptions(
            name='usershoppingcart',
            options={'verbose_name': 'Рецепт в корзине', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredientspecification',
            name='measurement_unit',
            field=models.CharField(max_length=200, verbose_name='Размерность'),
        ),
        migrations.AlterField(
            model_name='ingredientspecification',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.Ingredient', to='recipes.IngredientSpecification', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_favorited',
            field=models.ManyToManyField(related_name='favorite_recipes', through='recipes.UserFavoritedRecipe', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.ManyToManyField(related_name='shopping_cart', through='recipes.UserShoppingCart', to=settings.AUTH_USER_MODEL, verbose_name='В корзине'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(through='recipes.TagRecipe', to='recipes.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddConstraint(
            model_name='ingredientspecification',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='name_with_this_measurement_unit_alredy_exist'),
        ),
    ]
