# Generated by Django 3.2.3 on 2023-07-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientspecification',
            name='measurement_unit',
            field=models.CharField(max_length=32, verbose_name='Размерность'),
        ),
    ]
